version: "3.9"

services:
  neural-verification:
    container_name: marabou-tool
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/usr/src/app/data
    command: ["tail", "-f", "/dev/null"]
